.TH init 8
'''
.SH NAME
init \- system supervisor.
'''
.SH SYNOPSIS
/sbin/init [\fIkernel options\fR]
'''
.SH DESCRIPTION
\fBinit\fR is process #1, the only process kernel starts directly.
Upon startup, \fBinit\fR spawns processes to initialize and run the system.
\fBinit\fR process is not allowed to die.
.P
Additionally, \fBinit\fR adopts all orphaned processes in the system,
becoming their parent process and reaping them when they die.
'''
.SH USAGE
\fBinit\fR is started by the kernel and can not be killed by a user.
.P
All user communication with init occurs via its control socket,
see \fBtelinit\fR(8).
.P
Kernel passes any arguments it does not recognize to init.
Among those, "1", "2", ..., "9" set the default runlevel,
the rest are silently ignored.
.P
Check Documentation/kernel-parameters.txt, Documentation/init.txt from
the kernel source on how to pass arguments to kernel (and subsequently to init).
'''
.SH CONFIGURATION
\fBinit\fR reads the list of processes to spawn from \fBinittab\fR(5),
and (if enabled at compile time) \fBinitdir\fR(5). See those pages on
syntax as well as usage guidelines.
.P
The files are parsed early during system startup, and no attempts are made
to re-read them later. To initiate re-configuration after editing the file,
use "telinit q". See \fBtelinit\fR(8).
'''
.SH ENVIRONMENT
\fBinit\fR does not use any environment variables and does not pass any inherited
environment to child processes.
.P
The only variables processes spawned by init see are those set in \fBinittab\fR(5).
All spawned processes get exactly the same environment.
'''
.SH SIGNALS
\fBinit\fR attempts to reopen its control socket on SIGHUP. Other user signals are ignored.
'''
.SH FILES
.IP "{/etc/inittab}" 4
Primary configuration file. See \fB{inittab}\fR(5).
.IP "{/etc/initdir}" 4
Service directory. See \fB{initdir}\fR(5).
.IP "{@initctl}"
Unix domain socket, for telinit communication. See \fB{telinit}\fR(8) and \fBunix\fR(7).
'''
.SH NOTES
This page describes init from {INIT} package. Other implementations, in particular
sysvinit, behave somewhat differently.
'''
.SH SEE ALSO
\fB{telinit}\fR(8), \fB{inittab}\fR(5).
